# Generated by Django 4.2 on 2023-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromeExt', '0002_video_transcription_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='transcription_file',
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(default='pending'),
        ),
    ]
