# Generated by Django 4.2 on 2023-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chromeExt', '0005_alter_videosession_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='chunks',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
